name: Build Docker Images

on:
  push:
    branches:
      - main
    paths:
      - '*/version.txt'
      - '.github/workflows/build.yml'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get changed directories with version files
        id: changed-dirs
        run: |
          # For pushes to main, compare with the previous commit
          CHANGED_DIRS=$(git diff --name-only HEAD^ HEAD | grep -o "^[^/]*/version.txt" | sed 's/\/version.txt//' | sort | uniq | jq -R -s -c 'split("\n") | map(select(length > 0))')

          echo "Changed directories: $CHANGED_DIRS"
          echo "matrix=$CHANGED_DIRS" >> $GITHUB_OUTPUT

      - name: Set matrix
        id: set-matrix
        run: |
          MATRIX=$(echo '{"service": ${{ steps.changed-dirs.outputs.matrix }}}')
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: detect-changes
    strategy:
      matrix: ${{ fromJson(needs.detect-changes.outputs.matrix) }}
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get version
        id: get-version
        run: |
          VERSION=$(cat ${{ matrix.service }}/version.txt | tr -d '[:space:]')
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.service }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            thisisgain/${{ matrix.service }}:latest
            thisisgain/${{ matrix.service }}:${{ steps.get-version.outputs.VERSION }}
          labels: |
            org.opencontainers.image.documentation=https://github.com/${{ github.repository }}/blob/main/${{ matrix.service }}/README.md